
[[constraint]]
  branch = "testnet1"
  name = "github.com/hybridnetwork/hxd"

[[constraint]]
  branch = "dev-v0.0.1"
  name = "github.com/hybridnetwork/hxrpcclient"

[[constraint]]
  branch = "dev-v0.0.1"
  name = "github.com/hybridnetwork/hxutil"
